version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: kafka-nodejs-zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: kafka-nodejs-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: topqtbsx:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: postgres
    container_name: kafka-nodejs-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 8000:5432
  producer:
    build: ./services/producer
    container_name: kafka-nodejs-producer
    command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 npm start"
    depends_on:
      - zookeeper
      - kafka
    environment:
      PRODUCER_PORT: 8080
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 8080:8080
  consumer:
    build: ./services/consumer
    container_name: kafka-nodejs-consumer
    command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 -wait tcp://database:5432 npm start"
    depends_on:
        - zookeeper
        - kafka
        - database
    environment:
      PGHOST: database
      PGPORT: 5432
      PGUSER: root
      PGDATABASE: test_db
      PGPASSWORD: root
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
